import { SessionProvider } from "next-auth/react"
import { Inter } from "next/font/google"
import "./globals.css"
import { NextAuthProvider } from "./components/providers/session-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "jungyeon",
    description: "Generated by jungyeon",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    )
}
