server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  main:
    log-startup-info: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        security: debug